# Generated by Django 3.2.4 on 2021-08-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao', '0002_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
