# Generated by Django 3.2.4 on 2021-08-26 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100, null=True)),
                ('email', models.EmailField(default='', max_length=100)),
                ('telefone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('cep', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('endereco', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('uf', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('ampanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.empresa')),
            ],
            options={
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
    ]
