# Generated by Django 3.2.4 on 2021-08-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='ampanha',
        ),
    ]
